# Generated by Django 5.2.6 on 2025-09-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_in_stock_product_instock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='originalPrice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='review_count',
            new_name='reviewCount',
        ),
    ]
